### ISSUE TITLE
Can't install using node 9?

### ISSUE THREAD

**Issue by lougreenwood** [isleofcode/ember-cordova-splash#9]
Hi, I just tried adding this add-on and I received this error:

```
Command failed: yarn add --dev ember-cordova-splash --non-interactive
error ember-cordova-installer@0.0.3: The engine "node" is incompatible with this module. Expected version "^4.5 || 6.* || 7.* || 8.*".
error An unexpected error occurred: "Found incompatible module".

yarn add v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
```

Yarn error log is attached
[yarn-error.log](https://github.com/isleofcode/ember-cordova-splash/files/1883385/yarn-error.log)

**Comment by alexblom** [comment]
This should be fixed in 0.1.7. Please let me now if you continue to have issues.

**Comment by lougreenwood** [comment]
Seems likely that the PR you mentioned fixes this issue, however, it seems that it's still not possible to install the add-on because of this secondary error with node 10:

```
error ember-cordova-installer@0.0.4: The engine "node" is incompatible with this module. Expected version "^4.5 || 6.* || 7.* || 8.* || 9.*".
error Found incompatible module
```

I'll create an issue for `ember-cordova-installer`
